#include "simulator/vcd_writer.h"

#include <cstdio>
#include <cstring>

#include "simulator/variable.h"

namespace delta {

VcdWriter::VcdWriter(const std::string& filename) : ofs_(filename) {}

VcdWriter::~VcdWriter() {
  if (ofs_.is_open()) ofs_.close();
}

void VcdWriter::WriteHeader(std::string_view timescale,
                            std::string_view dumpfile_literal) {
  if (!ofs_.is_open()) return;
  ofs_ << "$date\n  Generated by DeltaHDL\n$end\n";
  // §21.7.2.3: the $version section names the VCD writer and the $dumpfile call
  // that created the file. When the filename was supplied by a variable or an
  // expression, the unevaluated literal is reproduced here rather than the
  // resolved name.
  ofs_ << "$version\n  DeltaHDL 0.1.0\n";
  if (!dumpfile_literal.empty()) {
    ofs_ << "  $dumpfile(" << dumpfile_literal << ")\n";
  }
  ofs_ << "$end\n";
  ofs_ << "$timescale\n  " << timescale << "\n$end\n";
  header_written_ = true;
}

void VcdWriter::BeginScope(std::string_view name, VcdScopeKind kind) {
  if (!ofs_.is_open()) return;
  // §21.7.5: an unpacked structure appears as a named fork-join block, so its
  // scope uses the fork keyword rather than module.
  const char* keyword = kind == VcdScopeKind::kFork ? "fork" : "module";
  ofs_ << "$scope " << keyword << " " << name << " $end\n";
}

void VcdWriter::EndScope() {
  if (!ofs_.is_open()) return;
  ofs_ << "$upscope $end\n";
}

// §21.7.2.3: choose the var_type keyword written in a $var declaration. Real
// variables are dumped as real numbers. A net declared with net type uwire is
// recorded as wire — uwire is not itself a var_type keyword — and this writer
// renders every other binary-valued net as wire as well.
static const char* VcdVarTypeKeyword(const VcdSignal& sig) {
  if (sig.var && sig.var->value.is_real) return "real";
  if (sig.net_type == NetType::kUwire) return "wire";
  return "wire";
}

// §21.7.5 (Table 21-11): map a SystemVerilog data type to the 1364-2005
// var_type keyword and the size it is dumped with. bit and logic keep the full
// packed width passed in (Table 21-11: "total size of packed dimension"), which
// also covers a packed array or structure collapsed to a single reg vector. The
// fixed-width integer types and the default enum carry the size fixed by the
// table regardless of the declared width. A net (kNet) keeps the §21.7.2.3
// keyword and its own width.
static const char* VcdDataTypeKeyword(VcdDataType type) {
  switch (type) {
    case VcdDataType::kBit:
    case VcdDataType::kLogic:
    case VcdDataType::kShortint:
    case VcdDataType::kLongint:
    case VcdDataType::kByte:
      return "reg";
    case VcdDataType::kInt:
    case VcdDataType::kEnum:
      return "integer";
    case VcdDataType::kReal:
      return "real";
    case VcdDataType::kNet:
      break;
  }
  return "wire";
}

static uint32_t VcdDataTypeSize(VcdDataType type, uint32_t width) {
  switch (type) {
    case VcdDataType::kInt:
    case VcdDataType::kEnum:
      return 32;
    case VcdDataType::kShortint:
      return 16;
    case VcdDataType::kLongint:
      return 64;
    case VcdDataType::kByte:
      return 8;
    case VcdDataType::kBit:
    case VcdDataType::kLogic:
    case VcdDataType::kReal:
    case VcdDataType::kNet:
      break;
  }
  return width;
}

void VcdWriter::RegisterSignal(std::string_view name, uint32_t width,
                               Variable* var, NetType net_type, int32_t msb,
                               int32_t lsb, VcdDataType data_type) {
  VcdSignal sig;
  sig.name = name;
  sig.width = width;
  sig.var = var;
  sig.ident = next_ident_++;
  sig.net_type = net_type;
  sig.data_type = data_type;
  sig.msb = msb;
  sig.lsb = lsb;
  // §21.7.4.2: the identifier code of a port is an integer that ascends in
  // one-unit increments for each port, in the order found in the module
  // declaration. Each registration is one such port.
  sig.port_id = next_port_id_++;

  if (next_ident_ > '~') next_ident_ = '!';
  signals_.push_back(sig);
  if (!ofs_.is_open()) return;
  if (port_nodes_) {
    // §21.7.4.2 (Syntax 21-28): $var port <size> <<id> <reference> $end. The
    // var_type keyword is always port; the size is the declared index range of
    // a bus or 1 for a single-bit port; the identifier code is the integer
    // preceded by <. At least one space separates each syntactical element.
    ofs_ << "$var port ";
    if (sig.msb >= 0 && sig.lsb >= 0) {
      ofs_ << "[" << sig.msb << ":" << sig.lsb << "]";
    } else {
      ofs_ << "1";
    }
    ofs_ << " <" << sig.port_id << " " << name << " $end\n";
    return;
  }
  // §21.7.5 (Table 21-11): a SystemVerilog data type masquerades as a 1364-2005
  // type. A net keeps the §21.7.2.3 mapping (and a real object dumped through
  // that path is still detected by its value); a data type uses its table
  // entry.
  const char* keyword = sig.data_type == VcdDataType::kNet
                            ? VcdVarTypeKeyword(sig)
                            : VcdDataTypeKeyword(sig.data_type);
  uint32_t size = VcdDataTypeSize(sig.data_type, width);
  ofs_ << "$var " << keyword << " " << size << " " << sig.ident << " " << name
       << " $end\n";
}

void VcdWriter::EndDefinitions() {
  if (!ofs_.is_open()) return;
  ofs_ << "$enddefinitions $end\n";
}

bool VcdWriter::AtSizeLimit() {
  if (size_limit_ == 0) return false;  // no limit configured
  if (limit_reached_) return true;     // already stopped
  if (!ofs_.is_open()) return false;
  std::streampos pos = ofs_.tellp();
  if (pos == std::streampos(-1)) return false;
  if (static_cast<uint64_t>(pos) < size_limit_) return false;
  // The file has reached the requested byte count: note it in the dump and stop
  // recording any further value changes.
  ofs_ << "$comment\n  Dump limit of " << size_limit_
       << " bytes reached, dumping stopped.\n$end\n";
  limit_reached_ = true;
  return true;
}

void VcdWriter::WriteTimestamp(uint64_t time) {
  if (!ofs_.is_open() || !enabled_) return;
  if (AtSizeLimit()) return;
  ofs_ << "#" << time << "\n";
  last_time_ = time;
}

void VcdWriter::WriteScalarChange(const VcdSignal& sig) {
  if (!sig.var) return;
  uint64_t aval = sig.var->value.ToUint64() & 1;
  uint64_t bval = 0;
  if (sig.var->value.nwords > 0) {
    bval = sig.var->value.words[0].bval & 1;
  }
  char val = '0';
  if (!bval && aval) {
    val = '1';
  } else if (bval && !aval) {
    val = 'x';
  } else if (bval && aval) {
    val = 'z';
  }
  ofs_ << val << sig.ident << "\n";
}

// Table 21-8: a shortened vector value is reconstructed by left-extending it
// according to its most significant retained digit. The values 0 and 1 extend
// with 0, an x extends with x, and a z extends with z.
static char VcdLeftExtendFill(char digit) {
  if (digit == 'x') return 'x';
  if (digit == 'z') return 'z';
  return '0';
}

void VcdWriter::WriteVectorChange(const VcdSignal& sig) {
  if (!sig.var) return;
  // Build the full-width value with the most significant bit first.
  std::string digits;
  digits.reserve(sig.width);
  for (int32_t i = static_cast<int32_t>(sig.width) - 1; i >= 0; --i) {
    uint32_t word_idx = static_cast<uint32_t>(i) / 64;
    uint32_t bit_idx = static_cast<uint32_t>(i) % 64;
    uint64_t mask = uint64_t{1} << bit_idx;
    bool a = false;
    bool b = false;
    if (word_idx < sig.var->value.nwords) {
      a = (sig.var->value.words[word_idx].aval & mask) != 0;
      b = (sig.var->value.words[word_idx].bval & mask) != 0;
    }
    if (!b && !a) {
      digits.push_back('0');
    } else if (!b && a) {
      digits.push_back('1');
    } else if (b && !a) {
      digits.push_back('x');
    } else {
      digits.push_back('z');
    }
  }
  // §21.7.2.2: vectors are written in the shortest right-justified form. A
  // leading digit is redundant when the left-extension rule applied to the
  // digit that would replace it regenerates that leading digit, so drop such
  // digits while always keeping at least one.
  size_t start = 0;
  while (start + 1 < digits.size() &&
         digits[start] == VcdLeftExtendFill(digits[start + 1])) {
    ++start;
  }
  // No white space between the base letter and the value digits, and exactly
  // one white space between the value digits and the identifier code.
  ofs_ << 'b' << (digits.c_str() + start) << ' ' << sig.ident << "\n";
}

void VcdWriter::WriteRealChange(const VcdSignal& sig) {
  if (!sig.var) return;
  // The stored value is the IEEE Std 754 double-precision bit pattern; recover
  // the number and print it with %.16g so the full 53-bit mantissa survives the
  // round-trip through the dump file.
  uint64_t bits = sig.var->value.ToUint64();
  double d = 0.0;
  std::memcpy(&d, &bits, sizeof(double));
  char buf[64];
  std::snprintf(buf, sizeof(buf), "%.16g", d);
  ofs_ << "r" << buf << " " << sig.ident << "\n";
}

void VcdWriter::WritePortValueChange(const VcdSignal& sig) {
  if (!sig.var) return;
  // §21.7.4.3 (Syntax 21-29): value ::= p port_value 0_strength_component
  // 1_strength_component. The key character p marks a port and is written with
  // no space before the port_value.
  ofs_ << 'p';
  // port_value: the binary state of the port (§21.7.4.1 — port values are given
  // in binary form as 0, 1, x, or z). The extended format dumps the whole
  // vector, most significant bit first; a scalar contributes a single state
  // character.
  bool driven = false;
  for (int32_t i = static_cast<int32_t>(sig.width) - 1; i >= 0; --i) {
    uint32_t word_idx = static_cast<uint32_t>(i) / 64;
    uint32_t bit_idx = static_cast<uint32_t>(i) % 64;
    uint64_t mask = uint64_t{1} << bit_idx;
    bool a = false;
    bool b = false;
    if (word_idx < sig.var->value.nwords) {
      a = (sig.var->value.words[word_idx].aval & mask) != 0;
      b = (sig.var->value.words[word_idx].bval & mask) != 0;
    }
    char c;
    if (!b && !a) {
      c = '0';
    } else if (!b && a) {
      c = '1';
    } else if (b && !a) {
      c = 'x';
    } else {
      c = 'z';
    }
    if (c != 'z') driven = true;
    ofs_ << c;
  }
  // The strength0 and strength1 components are each one of the eight
  // SystemVerilog strength values, encoded as the digit 0 highz, 1 small, 2
  // medium, 3 weak, 4 large, 5 pull, 6 strong, 7 supply. The model does not
  // track per-port drive strength, so a driven port is reported at strong
  // strength and a high-impedance port at highz strength for both components.
  char strength = driven ? '6' : '0';
  ofs_ << strength << strength;
  // identifier_code: the port's integer code preceded by <, exactly as written
  // in its $var declaration (§21.7.4.2). One space separates the value from it.
  ofs_ << " <" << sig.port_id << "\n";
}

void VcdWriter::WriteSignalChange(const VcdSignal& sig) {
  if (sig.var && sig.var->value.is_real) {
    WriteRealChange(sig);
  } else if (port_nodes_) {
    // §21.7.4.3: an extended VCD file produced by $dumpports records value
    // changes in the port form (p<port_value> with strength components and the
    // integer identifier code) rather than the 4-state form.
    WritePortValueChange(sig);
  } else if (sig.width == 1) {
    WriteScalarChange(sig);
  } else {
    WriteVectorChange(sig);
  }
}

void VcdWriter::WriteSignalAllX(const VcdSignal& sig) {
  if (sig.width == 1) {
    ofs_ << "x" << sig.ident << "\n";
  } else {
    ofs_ << "bx " << sig.ident << "\n";
  }
}

static bool HasValueChanged(const VcdSignal& sig) {
  for (uint32_t w = 0; w < sig.var->value.nwords; ++w) {
    if (sig.var->value.words[w].aval != sig.var->prev_value.words[w].aval ||
        sig.var->value.words[w].bval != sig.var->prev_value.words[w].bval) {
      return true;
    }
  }
  return false;
}

void VcdWriter::DumpAllValues() {
  if (!ofs_.is_open() || !enabled_) return;
  if (AtSizeLimit()) return;
  ofs_ << "$dumpvars\n";
  for (const auto& sig : signals_) {
    WriteSignalChange(sig);
  }
  ofs_ << "$end\n";
}

void VcdWriter::DumpSelectedValues(const std::vector<std::string_view>& names) {
  if (!ofs_.is_open() || !enabled_) return;
  if (AtSizeLimit()) return;
  ofs_ << "$dumpvars\n";
  for (const auto& sig : signals_) {
    bool wanted = false;
    for (auto name : names) {
      if (sig.name == name) {
        wanted = true;
        break;
      }
    }
    if (wanted) WriteSignalChange(sig);
  }
  ofs_ << "$end\n";
}

void VcdWriter::DumpAll() {
  if (!ofs_.is_open() || !enabled_) return;
  if (AtSizeLimit()) return;
  // The checkpoint records the present value of every selected variable,
  // regardless of whether that value changed during the current time step.
  ofs_ << "$dumpall\n";
  for (const auto& sig : signals_) {
    WriteSignalChange(sig);
  }
  ofs_ << "$end\n";
}

void VcdWriter::DumpOff() {
  if (!ofs_.is_open()) return;
  // The checkpoint records every selected variable as x, then dumping stops so
  // that no value changes are recorded until $dumpon is executed.
  ofs_ << "$dumpoff\n";
  for (const auto& sig : signals_) {
    WriteSignalAllX(sig);
  }
  ofs_ << "$end\n";
  enabled_ = false;
}

void VcdWriter::DumpOn() {
  if (!ofs_.is_open()) return;
  // Recording resumes and a checkpoint of each variable's value at this time is
  // emitted so the dump reflects the current state.
  enabled_ = true;
  ofs_ << "$dumpon\n";
  for (const auto& sig : signals_) {
    WriteSignalChange(sig);
  }
  ofs_ << "$end\n";
}

void VcdWriter::Flush() {
  if (!ofs_.is_open()) return;
  // Empty the stream's buffer into the file so its current contents are
  // observable to an external reader. No dump command is written and the
  // enabled state is left as it was, so dumping resumes seamlessly.
  ofs_.flush();
}

void VcdWriter::WriteVcdClose(uint64_t final_time) {
  if (!ofs_.is_open() || !extended_) return;
  // §21.7.3.6.1: the final keyword command of an extended VCD file marks the
  // end simulation time at the moment the file is closed. The time is written
  // as a value-change-style timestamp (#<time>), so the recorded end time
  // stands on its own even when no signal changed at that time.
  ofs_ << "$vcdclose #" << final_time << " $end\n";
}

void VcdWriter::DumpChangedValues(uint64_t) {
  if (!ofs_.is_open() || !enabled_) return;
  if (AtSizeLimit()) return;
  for (const auto& sig : signals_) {
    if (!sig.var) continue;
    if (!HasValueChanged(sig)) continue;
    WriteSignalChange(sig);
  }
}

}  // namespace delta
