// §12.4.2.1: Violation reports generated by unique-if, unique0-if, and
// priority-if constructs — deferred reporting and glitch immunity.

#include "fixture_simulator.h"
#include "simulator/lowerer.h"
#include "simulator/process.h"
#include "simulator/stmt_exec.h"

using namespace delta;

namespace {

// §12.4.2.1: Violations are deferred to the Observed region. An initial block
// overlap violation should still be reported after the scheduler drains.
TEST(SimA60421, DeferredOverlapViolationReported) {
  SimFixture f;
  auto* design = ElaborateSrc(
      "module t;\n"
      "  logic [7:0] x;\n"
      "  initial begin\n"
      "    unique if (1) x = 8'd10;\n"
      "    else if (1) x = 8'd20;\n"
      "  end\n"
      "endmodule\n",
      f);
  ASSERT_NE(design, nullptr);
  Lowerer lowerer(f.ctx, f.arena, f.diag);
  lowerer.Lower(design);
  f.scheduler.Run();
  // Overlap violation deferred to Observed region and matured.
  EXPECT_GE(f.diag.WarningCount(), 1u);
}

// §12.4.2.1: Deferred no-match violation from priority-if in initial block.
TEST(SimA60421, DeferredPriorityNoMatchReported) {
  SimFixture f;
  auto* design = ElaborateSrc(
      "module t;\n"
      "  logic [7:0] x;\n"
      "  initial begin\n"
      "    x = 8'd0;\n"
      "    priority if (0) x = 8'd10;\n"
      "    else if (0) x = 8'd20;\n"
      "  end\n"
      "endmodule\n",
      f);
  ASSERT_NE(design, nullptr);
  Lowerer lowerer(f.ctx, f.arena, f.diag);
  lowerer.Lower(design);
  f.scheduler.Run();
  EXPECT_EQ(f.diag.WarningCount(), 1u);
}

// §12.4.2.1: FlushPendingViolations clears pending violations so the Observed
// region callback finds nothing to report.
TEST(SimA60421, FlushClearsPendingViolations) {
  SimFixture f;

  // Create a process so AddPendingViolation stores to it.
  Process proc;
  proc.kind = ProcessKind::kInitial;
  f.ctx.SetCurrentProcess(&proc);

  f.ctx.AddPendingViolation("test violation");
  ASSERT_EQ(proc.pending_violations.size(), 1u);

  // Flush clears the pending list — simulates re-trigger glitch immunity.
  f.ctx.FlushPendingViolations();
  EXPECT_TRUE(proc.pending_violations.empty());

  // Run the scheduler; the Observed callback should find an empty vector.
  f.scheduler.Run();
  EXPECT_EQ(f.diag.WarningCount(), 0u);

  f.ctx.SetCurrentProcess(nullptr);
}

// §12.4.2.1: MaturePendingViolations immediately reports and clears.
TEST(SimA60421, MatureReportsImmediately) {
  SimFixture f;

  Process proc;
  proc.kind = ProcessKind::kInitial;
  f.ctx.SetCurrentProcess(&proc);

  proc.pending_violations.push_back("mature test");
  f.ctx.MaturePendingViolations();

  EXPECT_TRUE(proc.pending_violations.empty());
  EXPECT_EQ(f.diag.WarningCount(), 1u);

  f.ctx.SetCurrentProcess(nullptr);
}

// §12.4.2.1: Multiple violations accumulate and all mature together.
TEST(SimA60421, MultipleViolationsMature) {
  SimFixture f;

  Process proc;
  proc.kind = ProcessKind::kInitial;
  f.ctx.SetCurrentProcess(&proc);

  f.ctx.AddPendingViolation("violation 1");
  f.ctx.AddPendingViolation("violation 2");
  ASSERT_EQ(proc.pending_violations.size(), 2u);

  // Run scheduler to execute Observed region callbacks.
  f.scheduler.Run();
  EXPECT_EQ(f.diag.WarningCount(), 2u);

  f.ctx.SetCurrentProcess(nullptr);
}

// §12.4.2.1: Flush after partial accumulation only clears what is pending.
TEST(SimA60421, FlushAfterPartialAccumulation) {
  SimFixture f;

  Process proc;
  proc.kind = ProcessKind::kInitial;
  f.ctx.SetCurrentProcess(&proc);

  f.ctx.AddPendingViolation("will be flushed");
  f.ctx.FlushPendingViolations();

  // Add a new violation after flush — this one should survive.
  f.ctx.AddPendingViolation("will mature");

  f.scheduler.Run();
  // Only the second violation should have been reported. The first Observed
  // callback finds an empty vector (flushed), the second finds "will mature".
  EXPECT_EQ(f.diag.WarningCount(), 1u);

  f.ctx.SetCurrentProcess(nullptr);
}

}  // namespace
