#include "lexer/keywords.h"

#include <unordered_map>

namespace delta {
namespace {

// clang-format off
const std::unordered_map<std::string_view, TokenKind> kKeywordMap = {
    {"accept_on", TokenKind::kKwAcceptOn},
    {"alias", TokenKind::kKwAlias},
    {"always", TokenKind::kKwAlways},
    {"always_comb", TokenKind::kKwAlwaysComb},
    {"always_ff", TokenKind::kKwAlwaysFF},
    {"always_latch", TokenKind::kKwAlwaysLatch},
    {"and", TokenKind::kKwAnd},
    {"assert", TokenKind::kKwAssert},
    {"assign", TokenKind::kKwAssign},
    {"assume", TokenKind::kKwAssume},
    {"automatic", TokenKind::kKwAutomatic},
    {"before", TokenKind::kKwBefore},
    {"begin", TokenKind::kKwBegin},
    {"bind", TokenKind::kKwBind},
    {"bins", TokenKind::kKwBins},
    {"binsof", TokenKind::kKwBinsof},
    {"bit", TokenKind::kKwBit},
    {"break", TokenKind::kKwBreak},
    {"buf", TokenKind::kKwBuf},
    {"bufif0", TokenKind::kKwBufif0},
    {"bufif1", TokenKind::kKwBufif1},
    {"byte", TokenKind::kKwByte},
    {"case", TokenKind::kKwCase},
    {"casex", TokenKind::kKwCasex},
    {"casez", TokenKind::kKwCasez},
    {"cell", TokenKind::kKwCell},
    {"chandle", TokenKind::kKwChandle},
    {"checker", TokenKind::kKwChecker},
    {"class", TokenKind::kKwClass},
    {"clocking", TokenKind::kKwClocking},
    {"cmos", TokenKind::kKwCmos},
    {"config", TokenKind::kKwConfig},
    {"const", TokenKind::kKwConst},
    {"constraint", TokenKind::kKwConstraint},
    {"context", TokenKind::kKwContext},
    {"continue", TokenKind::kKwContinue},
    {"cover", TokenKind::kKwCover},
    {"covergroup", TokenKind::kKwCovergroup},
    {"coverpoint", TokenKind::kKwCoverpoint},
    {"cross", TokenKind::kKwCross},
    {"deassign", TokenKind::kKwDeassign},
    {"default", TokenKind::kKwDefault},
    {"defparam", TokenKind::kKwDefparam},
    {"design", TokenKind::kKwDesign},
    {"disable", TokenKind::kKwDisable},
    {"dist", TokenKind::kKwDist},
    {"do", TokenKind::kKwDo},
    {"edge", TokenKind::kKwEdge},
    {"else", TokenKind::kKwElse},
    {"end", TokenKind::kKwEnd},
    {"endcase", TokenKind::kKwEndcase},
    {"endchecker", TokenKind::kKwEndchecker},
    {"endclass", TokenKind::kKwEndclass},
    {"endclocking", TokenKind::kKwEndclocking},
    {"endconfig", TokenKind::kKwEndconfig},
    {"endfunction", TokenKind::kKwEndfunction},
    {"endgenerate", TokenKind::kKwEndgenerate},
    {"endgroup", TokenKind::kKwEndgroup},
    {"endinterface", TokenKind::kKwEndinterface},
    {"endmodule", TokenKind::kKwEndmodule},
    {"endpackage", TokenKind::kKwEndpackage},
    {"endprimitive", TokenKind::kKwEndprimitive},
    {"endprogram", TokenKind::kKwEndprogram},
    {"endproperty", TokenKind::kKwEndproperty},
    {"endsequence", TokenKind::kKwEndsequence},
    {"endspecify", TokenKind::kKwEndspecify},
    {"endtable", TokenKind::kKwEndtable},
    {"endtask", TokenKind::kKwEndtask},
    {"enum", TokenKind::kKwEnum},
    {"event", TokenKind::kKwEvent},
    {"eventually", TokenKind::kKwEventually},
    {"expect", TokenKind::kKwExpect},
    {"export", TokenKind::kKwExport},
    {"extends", TokenKind::kKwExtends},
    {"extern", TokenKind::kKwExtern},
    {"final", TokenKind::kKwFinal},
    {"first_match", TokenKind::kKwFirstMatch},
    {"for", TokenKind::kKwFor},
    {"force", TokenKind::kKwForce},
    {"foreach", TokenKind::kKwForeach},
    {"forever", TokenKind::kKwForever},
    {"fork", TokenKind::kKwFork},
    {"forkjoin", TokenKind::kKwForkjoin},
    {"function", TokenKind::kKwFunction},
    {"generate", TokenKind::kKwGenerate},
    {"genvar", TokenKind::kKwGenvar},
    {"global", TokenKind::kKwGlobal},
    {"highz0", TokenKind::kKwHighz0},
    {"highz1", TokenKind::kKwHighz1},
    {"if", TokenKind::kKwIf},
    {"iff", TokenKind::kKwIff},
    {"ifnone", TokenKind::kKwIfnone},
    {"ignore_bins", TokenKind::kKwIgnoreBins},
    {"illegal_bins", TokenKind::kKwIllegalBins},
    {"implements", TokenKind::kKwImplements},
    {"implies", TokenKind::kKwImplies},
    {"import", TokenKind::kKwImport},
    {"incdir", TokenKind::kKwIncdir},
    {"include", TokenKind::kKwInclude},
    {"initial", TokenKind::kKwInitial},
    {"inout", TokenKind::kKwInout},
    {"input", TokenKind::kKwInput},
    {"inside", TokenKind::kKwInside},
    {"instance", TokenKind::kKwInstance},
    {"int", TokenKind::kKwInt},
    {"integer", TokenKind::kKwInteger},
    {"interconnect", TokenKind::kKwInterconnect},
    {"interface", TokenKind::kKwInterface},
    {"intersect", TokenKind::kKwIntersect},
    {"join", TokenKind::kKwJoin},
    {"join_any", TokenKind::kKwJoinAny},
    {"join_none", TokenKind::kKwJoinNone},
    {"large", TokenKind::kKwLarge},
    {"let", TokenKind::kKwLet},
    {"liblist", TokenKind::kKwLiblist},
    {"library", TokenKind::kKwLibrary},
    {"local", TokenKind::kKwLocal},
    {"localparam", TokenKind::kKwLocalparam},
    {"logic", TokenKind::kKwLogic},
    {"longint", TokenKind::kKwLongint},
    {"macromodule", TokenKind::kKwMacromodule},
    {"matches", TokenKind::kKwMatches},
    {"medium", TokenKind::kKwMedium},
    {"modport", TokenKind::kKwModport},
    {"module", TokenKind::kKwModule},
    {"nand", TokenKind::kKwNand},
    {"negedge", TokenKind::kKwNegedge},
    {"nettype", TokenKind::kKwNettype},
    {"new", TokenKind::kKwNew},
    {"nexttime", TokenKind::kKwNexttime},
    {"nmos", TokenKind::kKwNmos},
    {"nor", TokenKind::kKwNor},
    {"noshowcancelled", TokenKind::kKwNoshowcancelled},
    {"not", TokenKind::kKwNot},
    {"notif0", TokenKind::kKwNotif0},
    {"notif1", TokenKind::kKwNotif1},
    {"null", TokenKind::kKwNull},
    {"or", TokenKind::kKwOr},
    {"output", TokenKind::kKwOutput},
    {"package", TokenKind::kKwPackage},
    {"packed", TokenKind::kKwPacked},
    {"parameter", TokenKind::kKwParameter},
    {"pmos", TokenKind::kKwPmos},
    {"posedge", TokenKind::kKwPosedge},
    {"primitive", TokenKind::kKwPrimitive},
    {"priority", TokenKind::kKwPriority},
    {"program", TokenKind::kKwProgram},
    {"property", TokenKind::kKwProperty},
    {"protected", TokenKind::kKwProtected},
    {"pull0", TokenKind::kKwPull0},
    {"pull1", TokenKind::kKwPull1},
    {"pulldown", TokenKind::kKwPulldown},
    {"pullup", TokenKind::kKwPullup},
    {"pulsestyle_ondetect", TokenKind::kKwPulsestyleOndetect},
    {"pulsestyle_onevent", TokenKind::kKwPulsestyleOnevent},
    {"pure", TokenKind::kKwPure},
    {"rand", TokenKind::kKwRand},
    {"randc", TokenKind::kKwRandc},
    {"randcase", TokenKind::kKwRandcase},
    {"randsequence", TokenKind::kKwRandsequence},
    {"rcmos", TokenKind::kKwRcmos},
    {"real", TokenKind::kKwReal},
    {"realtime", TokenKind::kKwRealtime},
    {"ref", TokenKind::kKwRef},
    {"reg", TokenKind::kKwReg},
    {"reject_on", TokenKind::kKwRejectOn},
    {"release", TokenKind::kKwRelease},
    {"repeat", TokenKind::kKwRepeat},
    {"restrict", TokenKind::kKwRestrict},
    {"return", TokenKind::kKwReturn},
    {"rnmos", TokenKind::kKwRnmos},
    {"rpmos", TokenKind::kKwRpmos},
    {"rtran", TokenKind::kKwRtran},
    {"rtranif0", TokenKind::kKwRtranif0},
    {"rtranif1", TokenKind::kKwRtranif1},
    {"s_always", TokenKind::kKwSAlways},
    {"s_eventually", TokenKind::kKwSEventually},
    {"s_nexttime", TokenKind::kKwSNexttime},
    {"s_until", TokenKind::kKwSUntil},
    {"s_until_with", TokenKind::kKwSUntilWith},
    {"scalared", TokenKind::kKwScalared},
    {"sequence", TokenKind::kKwSequence},
    {"shortint", TokenKind::kKwShortint},
    {"shortreal", TokenKind::kKwShortreal},
    {"showcancelled", TokenKind::kKwShowcancelled},
    {"signed", TokenKind::kKwSigned},
    {"small", TokenKind::kKwSmall},
    {"soft", TokenKind::kKwSoft},
    {"solve", TokenKind::kKwSolve},
    {"specify", TokenKind::kKwSpecify},
    {"specparam", TokenKind::kKwSpecparam},
    {"static", TokenKind::kKwStatic},
    {"string", TokenKind::kKwString},
    {"strong", TokenKind::kKwStrong},
    {"strong0", TokenKind::kKwStrong0},
    {"strong1", TokenKind::kKwStrong1},
    {"struct", TokenKind::kKwStruct},
    {"super", TokenKind::kKwSuper},
    {"supply0", TokenKind::kKwSupply0},
    {"supply1", TokenKind::kKwSupply1},
    {"sync_accept_on", TokenKind::kKwSyncAcceptOn},
    {"sync_reject_on", TokenKind::kKwSyncRejectOn},
    {"table", TokenKind::kKwTable},
    {"tagged", TokenKind::kKwTagged},
    {"task", TokenKind::kKwTask},
    {"this", TokenKind::kKwThis},
    {"throughout", TokenKind::kKwThroughout},
    {"time", TokenKind::kKwTime},
    {"timeprecision", TokenKind::kKwTimeprecision},
    {"timeunit", TokenKind::kKwTimeunit},
    {"tran", TokenKind::kKwTran},
    {"tranif0", TokenKind::kKwTranif0},
    {"tranif1", TokenKind::kKwTranif1},
    {"tri", TokenKind::kKwTri},
    {"tri0", TokenKind::kKwTri0},
    {"tri1", TokenKind::kKwTri1},
    {"triand", TokenKind::kKwTriand},
    {"trior", TokenKind::kKwTrior},
    {"trireg", TokenKind::kKwTrireg},
    {"type", TokenKind::kKwType},
    {"typedef", TokenKind::kKwTypedef},
    {"union", TokenKind::kKwUnion},
    {"unique", TokenKind::kKwUnique},
    {"unique0", TokenKind::kKwUnique0},
    {"unsigned", TokenKind::kKwUnsigned},
    {"until", TokenKind::kKwUntil},
    {"until_with", TokenKind::kKwUntilWith},
    {"untyped", TokenKind::kKwUntyped},
    {"use", TokenKind::kKwUse},
    {"uwire", TokenKind::kKwUwire},
    {"var", TokenKind::kKwVar},
    {"vectored", TokenKind::kKwVectored},
    {"virtual", TokenKind::kKwVirtual},
    {"void", TokenKind::kKwVoid},
    {"wait", TokenKind::kKwWait},
    {"wait_order", TokenKind::kKwWaitOrder},
    {"wand", TokenKind::kKwWand},
    {"weak", TokenKind::kKwWeak},
    {"weak0", TokenKind::kKwWeak0},
    {"weak1", TokenKind::kKwWeak1},
    {"while", TokenKind::kKwWhile},
    {"wildcard", TokenKind::kKwWildcard},
    {"wire", TokenKind::kKwWire},
    {"with", TokenKind::kKwWith},
    {"within", TokenKind::kKwWithin},
    {"wor", TokenKind::kKwWor},
    {"xnor", TokenKind::kKwXnor},
    {"xor", TokenKind::kKwXor},
};
// clang-format on

}  // namespace

std::optional<TokenKind> LookupKeyword(std::string_view text) {
  auto it = kKeywordMap.find(text);
  if (it != kKeywordMap.end()) {
    return it->second;
  }
  return std::nullopt;
}

std::string_view TokenKindName(TokenKind kind) {
  switch (kind) {
    case TokenKind::kEof:
      return "EOF";
    case TokenKind::kError:
      return "error";
    case TokenKind::kIntLiteral:
      return "integer literal";
    case TokenKind::kRealLiteral:
      return "real literal";
    case TokenKind::kTimeLiteral:
      return "time literal";
    case TokenKind::kStringLiteral:
      return "string literal";
    case TokenKind::kUnbasedUnsizedLiteral:
      return "unbased unsized literal";
    case TokenKind::kIdentifier:
      return "identifier";
    case TokenKind::kEscapedIdentifier:
      return "escaped identifier";
    case TokenKind::kSystemIdentifier:
      return "system identifier";
    case TokenKind::kSemicolon:
      return "';'";
    case TokenKind::kLParen:
      return "'('";
    case TokenKind::kRParen:
      return "')'";
    case TokenKind::kLBracket:
      return "'['";
    case TokenKind::kRBracket:
      return "']'";
    case TokenKind::kLBrace:
      return "'{'";
    case TokenKind::kRBrace:
      return "'}'";
    case TokenKind::kComma:
      return "','";
    case TokenKind::kDot:
      return "'.'";
    case TokenKind::kColon:
      return "':'";
    case TokenKind::kHash:
      return "'#'";
    case TokenKind::kEq:
      return "'='";
    case TokenKind::kLtEq:
      return "'<='";
    case TokenKind::kApostrophe:
      return "'";
    case TokenKind::kApostropheLBrace:
      return "'{";
    case TokenKind::kAttrStart:
      return "'(*'";
    case TokenKind::kAttrEnd:
      return "'*)'";
    default:
      return "token";
  }
}

}  // namespace delta
